learning_logs/urls.py
"""定义 learning_logs 的 URL 模块"""

from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    # 主页
    path('', views.index, name='index'),
    # # 显示所有的主题
    # path('topics/', views.topics, name='topics'),
    # # 显示单个主题及其所有的条目
    # path('topics/<int:topic_id>/', views.topic, name='topic'),
    # # 用于添加新主题的网页
    # path('new_topic/', views.new_topic, name='new_topic'),
    # # 用于添加新条目的网页
    # path()
]

ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
]

learning_logs/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def _str_(self):
        """返回模型的字符串表示"""
        return  self.text

class Entry(models.Model):
    """学到的每个主题的具体知识"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

        def _str_(self):
            """返回模型的字符串表示"""
            return f"{self.text[:50]}"

learning_logs/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    """学习笔记的主页"""
    return render(request, 'learning_logs/index.html')

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
</head>
<body>
    <p>
        <a href="{% url 'learning_logs:index' %}">首页</a>
    </p>
    {% block content %} {% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block title %}主页 - 学习笔记{% endblock %}

{% block content %}
    <h1>欢迎来到学习笔记！</h1>
    <p>这里是你的知识管理平台。</p>
{% endblock %}